version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      APP_ENV: development
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb

